backend:
  branch: master
  name: git-gateway
collections:
  - create: true
    fields:
      - { label: "Body", name: "body", required: true, width: "markdown" }
      - {
          label: "Publish Date",
          name: "date",
          required: true,
          widget: "datetime",
        }
      - { label: "Title", name: "title", required: true, widget: "string" }
    folder: "_content/posts"
    label: "Post"
    name: "post"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
media_folder: img
